#! /bin/sh


# autorun here
picom -f &
xsetroot -cursor_name left_ptr
feh --randomize --bg-fill ~/Pictures
fcitx5 &

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a Code='^2'
bspc rule -a "clash for windows"='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc config bottom_padding      5
bspc config top_padding         30
bspc config left_padding        5
bspc config right_padding       5
